{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"TradeInformationBase\",\"DimTrade\",\"DimTrader\",\"DimProduct\",\"DimAccount\",\"DimCurrency\",\"DimDate\",\"FactTrade\",\"_Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "TradeInformationBase",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Step 1: Load data from the source Excel file",
          "    Source = Excel.Workbook(",
          "        File.Contents(\"C:\\Users\\Violent Gandhi\\OneDrive\\Interview Assesments\\Act Group - Senior BI Engineer\\trading_dataset.xlsx\"), ",
          "        null, ",
          "        true",
          "    ),",
          "    ",
          "    // Step 2: Select the specific sheet containing trade information",
          "    TradeInformationSheet = Source{[Item=\"Trade Information\", Kind=\"Sheet\"]}[Data],",
          "    ",
          "    // Step 3: Promote the first row to become column headers",
          "    PromotedHeaders = Table.PromoteHeaders(",
          "        TradeInformationSheet, ",
          "        [PromoteAllScalars=true]",
          "    ),",
          "    ",
          "    // Step 4: Apply appropriate data types to each column",
          "    ChangedType = Table.TransformColumnTypes(",
          "        PromotedHeaders,",
          "        {",
          "            {\"CompanyCode\", type text},",
          "            {\"TradelineNumber\", type text},",
          "            {\"Type\", type text},",
          "            {\"RecordSource\", type text},",
          "            {\"TradeType\", type text},",
          "            {\"TradelineStatus\", type text},",
          "            {\"Direction\", type text},",
          "            {\"MatchIndicator\", type text},",
          "            {\"DealDate\", type date},",
          "            {\"Closed Date\", type date},",
          "            {\"ProductNumber2\", type text},",
          "            {\"L1_ProductGroup\", type text},",
          "            {\"L2_Subgroup\", type text},",
          "            {\"L3_Category\", type text},",
          "            {\"L4_SubCategory\", type text},",
          "            {\"AccountName\", type text},",
          "            {\"Inter Company Account\", Int64.Type},",
          "            {\"Account Parent\", type text},",
          "            {\"Account Country\", type text},",
          "            {\"Trader\", type text},",
          "            {\"Job Position\", type text},",
          "            {\"Department\", type text},",
          "            {\"PnlSplitPercentage\", Int64.Type},",
          "            {\"Volume\", type number},",
          "            {\"UnitOfMeasure\", type text},",
          "            {\"Price\", type number},",
          "            {\"MtM Price\", type number},",
          "            {\"COGS\", type number},",
          "            {\"Revenue\", type number},",
          "            {\"PnL\", type number},",
          "            {\"Currency\", type text}",
          "        }",
          "    )",
          "in",
          "    ChangedType"
        ],
        "kind": "m",
        "lineageTag": "0f2c2b45-7a60-471e-b120-f791f866da7f"
      }
    ],
    "relationships": [
      {
        "name": "0cfc9088-6c0b-48d6-ae36-30b5b24cd951",
        "fromColumn": "Date",
        "fromTable": "DimDate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_71042a39-f11b-4f33-9030-995a4c5cc700"
      },
      {
        "name": "AutoDetected_d5895a51-ec55-45a5-a7a1-bc26fba15839",
        "fromColumn": "TradelineNumber",
        "fromTable": "FactTrade",
        "toColumn": "TradelineNumber",
        "toTable": "DimTrade"
      },
      {
        "name": "AutoDetected_b7038278-49e6-4ace-a6be-0b7e04d3d81c",
        "fromColumn": "Currency",
        "fromTable": "FactTrade",
        "toColumn": "Currency",
        "toTable": "DimCurrency"
      },
      {
        "name": "790835e8-f505-da20-aeb4-138bf4840302",
        "fromColumn": "TraderKey",
        "fromTable": "FactTrade",
        "toColumn": "TraderKey",
        "toTable": "DimTrader"
      },
      {
        "name": "f2cc394b-5cc1-fa69-6623-540aeed2d206",
        "fromColumn": "DealDate",
        "fromTable": "DimTrade",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "66450403-adfa-2a3a-55a7-f4941b87cdcc",
        "fromColumn": "ClosedDate",
        "fromTable": "DimTrade",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "AutoDetected_99a74b62-e8e9-4fd9-820b-c5d6a441f082",
        "fromColumn": "ProductKey",
        "fromTable": "FactTrade",
        "toColumn": "ProductKey",
        "toTable": "DimProduct"
      },
      {
        "name": "AutoDetected_5bbe8bb7-239e-4525-b1bf-22c709abe7d3",
        "fromColumn": "AccountKey",
        "fromTable": "FactTrade",
        "toColumn": "AccountKey",
        "toTable": "DimAccount"
      },
      {
        "name": "0f774e69-7e55-2e75-74f9-918d56bb408e",
        "fromColumn": "PnL",
        "fromTable": "FactTrade",
        "isActive": false,
        "toColumn": "ProductKey",
        "toTable": "DimProduct"
      }
    ],
    "sourceQueryCulture": "en-001",
    "tables": [
      {
        "name": "DateTableTemplate_16964ba2-0da8-491d-a1d9-ba81f9437a1b",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "39e0957c-beee-469a-b90c-08286f8aac60",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "78e4ea69-b2dd-42eb-aef1-e0fdaa32e2dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "27fc9b58-8562-4477-b89b-08a10d4e6411",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6a51fc5d-2315-4b46-bb6a-6136ea57fbe1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ef72a6a-5fe7-4fc9-9f4f-8395c0d2fbd9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6327c1fb-be92-4450-88e0-f86f36cddb97",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eb1f419a-9bc1-46d9-a0b4-19da0606856b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "601b8b26-f5bc-4482-b32d-a47c7a324e16",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a53a3115-2996-4989-9d10-8899c8691dfd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bb359b98-4be7-4b9d-aaab-cde7bd6a8886",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4a66ccf6-4202-4409-b430-b7674b354bc7",
                "ordinal": 3
              }
            ],
            "lineageTag": "6d9f183a-a283-4107-a1f3-495acf501120"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "72c02353-42f8-4e5c-bb15-304b0a581a44",
        "partitions": [
          {
            "name": "DateTableTemplate_16964ba2-0da8-491d-a1d9-ba81f9437a1b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DimTrade",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TradelineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e908377-aab4-4f11-ae10-7d6188a1e148",
            "sourceColumn": "TradelineNumber",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d66db213-98c1-400a-8b75-d95ef68e766b",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "TradeTypeCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74ce6202-181d-4333-9c00-65c465637f0a",
            "sourceColumn": "TradeTypeCategory",
            "summarizeBy": "none"
          },
          {
            "name": "RecordSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97cf122d-e93a-4f17-9047-d321cb7cc2aa",
            "sourceColumn": "RecordSource",
            "summarizeBy": "none"
          },
          {
            "name": "TradeType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10c5e7fe-5364-419e-9586-8311492dc003",
            "sourceColumn": "TradeType",
            "summarizeBy": "none"
          },
          {
            "name": "TradelineStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37bac06b-7ad6-425b-b46a-a816a96e02f4",
            "sourceColumn": "TradelineStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Direction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3980f30-6b52-42ba-812c-4ae805683447",
            "sourceColumn": "Direction",
            "summarizeBy": "none"
          },
          {
            "name": "MatchIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3bec08e-64c1-446b-ba48-d388392517d2",
            "sourceColumn": "MatchIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "DealDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "56a5aab7-560d-46b0-b6fc-c76c9f55f7a8",
            "sourceColumn": "DealDate",
            "summarizeBy": "none"
          },
          {
            "name": "ClosedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0bfa76c6-425f-4503-b3ae-a5e68712e357",
            "sourceColumn": "ClosedDate",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a70052d9-063f-4c46-814c-004a4de2e997",
        "partitions": [
          {
            "name": "DimTrade",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Load source",
                "    Source = TradeInformationBase,",
                "",
                "    // 2. Keep only columns needed for DimTrade (natural keys + attributes)",
                "    SelectedColumns =",
                "        Table.SelectColumns(",
                "            Source,",
                "            {",
                "                \"TradelineNumber\", \"CompanyCode\", \"Type\", \"RecordSource\",",
                "                \"TradeType\", \"TradelineStatus\", \"Direction\", \"MatchIndicator\",",
                "                \"DealDate\", \"Closed Date\"",
                "            }",
                "        ),",
                "",
                "    // 3. Rename columns to remove spaces + standardize casing",
                "    RenamedColumns =",
                "        Table.RenameColumns(",
                "            SelectedColumns,",
                "            {",
                "                {\"TradelineNumber\", \"TradelineNumber\"},",
                "                {\"CompanyCode\", \"CompanyCode\"},",
                "                {\"Type\", \"TradeTypeCategory\"},",
                "                {\"RecordSource\", \"RecordSource\"},",
                "                {\"TradeType\", \"TradeType\"},",
                "                {\"TradelineStatus\", \"TradelineStatus\"},",
                "                {\"Direction\", \"Direction\"},",
                "                {\"MatchIndicator\", \"MatchIndicator\"},",
                "                {\"DealDate\", \"DealDate\"},",
                "                {\"Closed Date\", \"ClosedDate\"}",
                "            }",
                "        ),",
                "",
                "    // 4. Remove duplicates — one trade master row per TradelineNumber",
                "    DistinctRows = Table.Distinct(RenamedColumns)",
                "in",
                "    DistinctRows"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimTrader",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TraderName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ee0707b-2fb4-420f-af70-84be643b34d7",
            "sourceColumn": "TraderName",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54b50d86-0992-4ca8-8f04-0bf811d93e1f",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "JobPosition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d553a320-d067-4634-9640-7b72ec8abd3d",
            "sourceColumn": "JobPosition",
            "summarizeBy": "none"
          },
          {
            "name": "TraderKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86c02af8-665d-467e-bf36-e926830be89a",
            "sourceColumn": "TraderKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1f56d243-51c7-4783-962e-2bb10e4ce927",
        "partitions": [
          {
            "name": "DimTrader",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Start from base trading table",
                "    Source =",
                "        TradeInformationBase,",
                "",
                "    // 2. Keep only the columns needed for DimTrader",
                "    SelectedColumns =",
                "        Table.SelectColumns(",
                "            Source,",
                "            {\"Trader\", \"Job Position\", \"Department\"}",
                "        ),",
                "",
                "    // 3. Remove duplicate Trader + Job Position + Department combinations",
                "    DistinctTraders =",
                "        Table.Distinct(SelectedColumns),",
                "",
                "    // 4. Rename columns to remove spaces and standardise casing",
                "    RenamedColumns =",
                "        Table.RenameColumns(",
                "            DistinctTraders,",
                "            {",
                "                {\"Trader\", \"TraderName\"},",
                "                {\"Job Position\", \"JobPosition\"}",
                "            }",
                "        ),",
                "",
                "    // 5. Add a composite business key (TraderName + Department)",
                "    AddedBusinessKey =",
                "        Table.AddColumn(",
                "            RenamedColumns,",
                "            \"TraderKey\",",
                "            each [TraderName] & \"-\" & [Department],",
                "            type text",
                "        ),",
                "",
                "    // 6. Reorder columns for readability",
                "    ReorderedColumns =",
                "        Table.ReorderColumns(",
                "            AddedBusinessKey,",
                "            {\"TraderKey\", \"TraderName\", \"JobPosition\", \"Department\"}",
                "        )",
                "in",
                "    ReorderedColumns"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f6b4b5d-e74c-4fbb-bac4-dd7789f3ece4",
            "sourceColumn": "ProductNumber",
            "summarizeBy": "none"
          },
          {
            "name": "L1ProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "384aee87-0ae0-475b-9468-832950f584aa",
            "sourceColumn": "L1ProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "L2Subgroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ed98d9d-f616-43ad-b10e-287a93ff0630",
            "sourceColumn": "L2Subgroup",
            "summarizeBy": "none"
          },
          {
            "name": "L3Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "171bbf9f-95a4-4b64-aba1-bece0bf97f21",
            "sourceColumn": "L3Category",
            "summarizeBy": "none"
          },
          {
            "name": "L4SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddcfd99e-86d1-4b53-9174-55271f921575",
            "sourceColumn": "L4SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89cb4d62-ee21-4125-bd58-c10919eb6e59",
            "sourceColumn": "UnitOfMeasure",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4add7f0-4847-43ef-b9ef-1e9c6b4bc9b9",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "23be21c4-66f5-4163-96fd-51bad9cf163f",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Reference base source data",
                "    Source =",
                "        TradeInformationBase,",
                "",
                "    // 2. Keep only columns needed for DimProduct",
                "    SelectedColumns =",
                "        Table.SelectColumns(",
                "            Source,",
                "            {",
                "                \"ProductNumber2\",",
                "                \"L1_ProductGroup\",",
                "                \"L2_Subgroup\",",
                "                \"L3_Category\",",
                "                \"L4_SubCategory\",",
                "                \"UnitOfMeasure\"",
                "            }",
                "        ),",
                "",
                "    // 3. Remove duplicate products",
                "    DistinctProducts =",
                "        Table.Distinct(SelectedColumns),",
                "",
                "    // 4. Rename columns to remove spaces and standardise naming",
                "    RenamedColumns =",
                "        Table.RenameColumns(",
                "            DistinctProducts,",
                "            {",
                "                {\"ProductNumber2\", \"ProductNumber\"},",
                "                {\"L1_ProductGroup\", \"L1ProductGroup\"},",
                "                {\"L2_Subgroup\", \"L2Subgroup\"},",
                "                {\"L3_Category\", \"L3Category\"},",
                "                {\"L4_SubCategory\", \"L4SubCategory\"},",
                "                {\"UnitOfMeasure\", \"UnitOfMeasure\"}",
                "            }",
                "        ),",
                "",
                "    // 5. Add composite business key (ProductNumber + UnitOfMeasure)",
                "    AddedProductKey =",
                "        Table.AddColumn(",
                "            RenamedColumns,",
                "            \"ProductKey\",",
                "            each [ProductNumber] & \"-\" & [UnitOfMeasure],",
                "            type text",
                "        ),",
                "",
                "    // 6. Reorder columns for readability",
                "    ReorderedColumns =",
                "        Table.ReorderColumns(",
                "            AddedProductKey,",
                "            {",
                "                \"ProductKey\",",
                "                \"ProductNumber\",",
                "                \"L1ProductGroup\",",
                "                \"L2Subgroup\",",
                "                \"L3Category\",",
                "                \"L4SubCategory\",",
                "                \"UnitOfMeasure\"",
                "            }",
                "        )",
                "in",
                "    ReorderedColumns"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimAccount",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AccountName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13747182-5f9b-4f47-a0f1-63f8fe9f8a63",
            "sourceColumn": "AccountName",
            "summarizeBy": "none"
          },
          {
            "name": "InterCompanyAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "623a29e7-a1f0-4bdc-a57d-14ec00b62099",
            "sourceColumn": "InterCompanyAccount",
            "summarizeBy": "none"
          },
          {
            "name": "AccountParent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d141c07-875d-4ae3-9433-99408baa3eb0",
            "sourceColumn": "AccountParent",
            "summarizeBy": "none"
          },
          {
            "name": "AccountCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7abe92ce-ed86-44dc-97c0-ce8186579f0d",
            "sourceColumn": "AccountCountry",
            "summarizeBy": "none"
          },
          {
            "name": "AccountKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a015a65-2d6a-45a3-b8d2-83a8f86dd23b",
            "sourceColumn": "AccountKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a7eec2be-a6d2-45f5-82cc-31d275319c61",
        "partitions": [
          {
            "name": "DimAccount",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Reference base source data",
                "    Source =",
                "        TradeInformationBase,",
                "",
                "    // 2. Keep only the columns needed for DimAccount",
                "    SelectedColumns =",
                "        Table.SelectColumns(",
                "            Source,",
                "            {",
                "                \"AccountName\",",
                "                \"Inter Company Account\",",
                "                \"Account Parent\",",
                "                \"Account Country\"",
                "            }",
                "        ),",
                "",
                "    // 3. Remove duplicate account rows",
                "    DistinctAccounts =",
                "        Table.Distinct(SelectedColumns),",
                "",
                "    // 4. Rename columns to remove spaces and standardise naming",
                "    RenamedColumns =",
                "        Table.RenameColumns(",
                "            DistinctAccounts,",
                "            {",
                "                {\"AccountName\", \"AccountName\"},",
                "                {\"Inter Company Account\", \"InterCompanyAccount\"},",
                "                {\"Account Parent\", \"AccountParent\"},",
                "                {\"Account Country\", \"AccountCountry\"}",
                "            }",
                "        ),",
                "",
                "    // 5. Add composite business key (AccountName + AccountParent)",
                "    AddedAccountKey =",
                "        Table.AddColumn(",
                "            RenamedColumns,",
                "            \"AccountKey\",",
                "            each [AccountName] & \"-\" & [AccountParent],",
                "            type text",
                "        ),",
                "",
                "    // 6. Reorder columns for readability",
                "    ReorderedColumns =",
                "        Table.ReorderColumns(",
                "            AddedAccountKey,",
                "            {",
                "                \"AccountKey\",",
                "                \"AccountName\",",
                "                \"InterCompanyAccount\",",
                "                \"AccountParent\",",
                "                \"AccountCountry\"",
                "            }",
                "        )",
                "in",
                "    ReorderedColumns"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCurrency",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ae8673f-88ae-48b9-920b-66e581916937",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6dc69462-841b-4d4b-906a-bebfa07b6a6b",
        "partitions": [
          {
            "name": "DimCurrency",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // Reference base source data",
                "    Source = TradeInformationBase,",
                "    ",
                "    // Reorder columns as per dimension design",
                "    ReorderedColumns = Table.ReorderColumns(",
                "        Source,",
                "        {",
                "            \"Currency\", \"AccountName\", \"Inter Company Account\", \"Account Parent\", ",
                "            \"Account Country\", \"ProductNumber2\", \"L1_ProductGroup\", \"L2_Subgroup\",",
                "            \"L3_Category\", \"L4_SubCategory\", \"UnitOfMeasure\", \"Trader\", ",
                "            \"Department\", \"TradelineNumber\", \"CompanyCode\", \"Type\", \"RecordSource\", ",
                "            \"TradeType\", \"TradelineStatus\", \"Direction\", \"MatchIndicator\", ",
                "            \"DealDate\", \"Closed Date\", \"Job Position\", \"PnlSplitPercentage\", ",
                "            \"Volume\", \"Price\", \"MtM Price\", \"COGS\", \"Revenue\", \"PnL\"",
                "        }",
                "    ),",
                "    ",
                "    // Remove unnecessary columns not needed for this dimension",
                "    RemovedColumns = Table.RemoveColumns(",
                "        ReorderedColumns,",
                "        {",
                "            \"AccountName\", \"Inter Company Account\", \"Account Parent\", ",
                "            \"Account Country\", \"ProductNumber2\", \"L1_ProductGroup\", ",
                "            \"L2_Subgroup\", \"L3_Category\", \"L4_SubCategory\", \"UnitOfMeasure\", ",
                "            \"Trader\", \"Department\", \"TradelineNumber\", \"CompanyCode\", \"Type\", ",
                "            \"RecordSource\", \"TradeType\", \"TradelineStatus\", \"Direction\", ",
                "            \"MatchIndicator\", \"DealDate\", \"Closed Date\", \"Job Position\", ",
                "            \"PnlSplitPercentage\", \"Volume\", \"Price\", \"MtM Price\", ",
                "            \"COGS\", \"Revenue\", \"PnL\"",
                "        }",
                "    ),",
                "    ",
                "    // Remove duplicate rows",
                "    RemovedDuplicates = Table.Distinct(RemovedColumns)",
                "in",
                "    RemovedDuplicates"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35e089a4-4032-4332-8931-0758e132528c",
            "sourceColumn": "DateKey",
            "summarizeBy": "count"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "60ea79af-520e-4364-892d-4243d17aa1bc",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_71042a39-f11b-4f33-9030-995a4c5cc700"
                },
                "isDefault": true,
                "relationship": "0cfc9088-6c0b-48d6-ae36-30b5b24cd951"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd1801dd-13f2-42e0-9df2-ecce3e3c76db",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "927c8419-d203-43d6-9b7c-219f93b01cc3",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06ae53c5-48de-4e4a-acd8-b62987ef3f34",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1db42c07-b49a-4f03-826a-d14d242d99a2",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthShortName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "743031d0-8857-423a-a740-6a0115dc36b7",
            "sourceColumn": "MonthShortName",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60dfc4b0-a6a8-4d3a-9061-b57f3d23e90d",
            "sourceColumn": "YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "WeekOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee08fdda-0689-49fa-87dd-9adb4d97ee23",
            "sourceColumn": "WeekOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68025588-1b16-415e-8750-802ee69db865",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc2aaa2e-eea3-4c17-bf6e-1af86bf12429",
            "sourceColumn": "DayOfWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95391517-a2e8-4ea9-849f-91c36ee836b0",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "IsWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4dd81ef0-bdb0-48ba-b583-fe8413fb3827",
            "sourceColumn": "IsWeekend",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cc86d627-01de-4db4-ad60-8212f4df5a46",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // === PARAMETERS ===",
                "    // Adjust these if you want a different date range",
                "    StartDate = #date(2018, 1, 1),",
                "    EndDate   = #date(2030, 12, 31),",
                "",
                "    // Generate a list of dates",
                "    DateList = List.Dates(",
                "        StartDate,",
                "        Duration.Days(EndDate - StartDate) + 1,",
                "        #duration(1, 0, 0, 0)",
                "    ),",
                "",
                "    // Turn into a table",
                "    DateTable = Table.FromList(",
                "        DateList,",
                "        Splitter.SplitByNothing(),",
                "        type table [Date = Date.Type]",
                "    ),",
                "",
                "    // Add basic date parts",
                "    AddYear = Table.AddColumn(DateTable, \"Year\", each Date.Year([Date]), Int64.Type),",
                "    AddMonth = Table.AddColumn(AddYear, \"Month\", each Date.Month([Date]), Int64.Type),",
                "    AddDay = Table.AddColumn(AddMonth, \"Day\", each Date.Day([Date]), Int64.Type),",
                "",
                "    // DateKey = yyyymmdd as int",
                "    AddDateKey = Table.AddColumn(",
                "        AddDay,",
                "        \"DateKey\",",
                "        each [Year] * 10000 + [Month] * 100 + [Day],",
                "        Int64.Type",
                "    ),",
                "",
                "    // Month name & short month name",
                "    AddMonthName = Table.AddColumn(",
                "        AddDateKey,",
                "        \"MonthName\",",
                "        each Date.ToText([Date], \"MMMM\"),",
                "        type text",
                "    ),",
                "    AddMonthShort = Table.AddColumn(",
                "        AddMonthName,",
                "        \"MonthShortName\",",
                "        each Date.ToText([Date], \"MMM\"),",
                "        type text",
                "    ),",
                "",
                "    // Quarter",
                "    AddQuarter = Table.AddColumn(",
                "        AddMonthShort,",
                "        \"Quarter\",",
                "        each Date.QuarterOfYear([Date]),",
                "        Int64.Type",
                "    ),",
                "",
                "    // YearMonth as text  YYYYMM",
                "    AddYearMonth = Table.AddColumn(",
                "        AddQuarter,",
                "        \"YearMonth\",",
                "        each Text.From([Year]) &",
                "             Text.PadStart(Text.From([Month]), 2, \"0\"),",
                "        type text",
                "    ),",
                "",
                "    // Week of year",
                "    AddWeekOfYear = Table.AddColumn(",
                "        AddYearMonth,",
                "        \"WeekOfYear\",",
                "        each Date.WeekOfYear([Date]),",
                "        Int64.Type",
                "    ),",
                "",
                "    // Day of week (1 = Monday, 7 = Sunday)",
                "    AddDayOfWeek = Table.AddColumn(",
                "        AddWeekOfYear,",
                "        \"DayOfWeek\",",
                "        each Date.DayOfWeek([Date], Day.Monday) + 1,",
                "        Int64.Type",
                "    ),",
                "",
                "    // Day of week name",
                "    AddDayOfWeekName = Table.AddColumn(",
                "        AddDayOfWeek,",
                "        \"DayOfWeekName\",",
                "        each Date.ToText([Date], \"dddd\"),",
                "        type text",
                "    ),",
                "",
                "    // Weekend flag (Saturday/Sunday)",
                "    AddIsWeekend = Table.AddColumn(",
                "        AddDayOfWeekName,",
                "        \"IsWeekend\",",
                "        each if [DayOfWeek] >= 6 then true else false,",
                "        type logical",
                "    ),",
                "",
                "    // Reorder columns",
                "    Reordered = Table.ReorderColumns(",
                "        AddIsWeekend,",
                "        {",
                "            \"DateKey\",",
                "            \"Date\",",
                "            \"Year\",",
                "            \"Quarter\",",
                "            \"Month\",",
                "            \"MonthName\",",
                "            \"MonthShortName\",",
                "            \"YearMonth\",",
                "            \"WeekOfYear\",",
                "            \"Day\",",
                "            \"DayOfWeek\",",
                "            \"DayOfWeekName\",",
                "            \"IsWeekend\"",
                "        }",
                "    )",
                "in",
                "    Reordered"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_71042a39-f11b-4f33-9030-995a4c5cc700",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "26ac8d30-07de-4b65-8624-1c774f18acd2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "86b04703-1441-4442-a03e-51e06bad0544",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e600031a-ba05-4398-8847-13e0c2ffc0d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "daea990e-9923-4980-9350-af6a785310e4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "734c6626-3ced-4814-a6f9-3b95e1cb4bd5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "296ca8e1-2637-4d11-b096-07faa3a2e1eb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8b59f338-2320-4402-a4be-0cbc4e22ff68",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "731c9237-eaca-489c-a6c3-f4af36b32e76",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d09e1940-8ca2-4de6-8c60-7773645170dd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2de9d342-075e-4ceb-8b5b-41877d3efba5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "69b4dc1a-ed58-496b-9db7-cc74c3801b2a",
                "ordinal": 3
              }
            ],
            "lineageTag": "834956d1-e417-4f8e-9314-54c0e8556c04"
          }
        ],
        "isHidden": true,
        "lineageTag": "dac8ff2b-4c28-4094-9850-80d6e2ac6b1a",
        "partitions": [
          {
            "name": "LocalDateTable_71042a39-f11b-4f33-9030-995a4c5cc700",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimDate'[Date])), 1, 1), Date(Year(MAX('DimDate'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "FactTrade",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TradelineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "794da5ec-2f0b-4381-811b-c3142f56e549",
            "sourceColumn": "TradelineNumber",
            "summarizeBy": "none"
          },
          {
            "name": "PnlSplitPercentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90e39d78-946f-4c35-8cb2-fbd7e6708ef9",
            "sourceColumn": "PnlSplitPercentage",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2d04806-19e4-40d0-ae2b-0072592b0c40",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e04eacb-9248-4b14-9299-9c1a76f17633",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "MtM Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0970e58b-bbe7-4a97-98ae-3df4fddf5fb7",
            "sourceColumn": "MtM Price",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b05a028-0c78-487d-9aa9-ee621fd96320",
            "sourceColumn": "COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2b7deae-7818-412b-bb6f-6098c9a87293",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "PnL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb4a0a6b-d00f-4be7-8318-e7061f641c11",
            "sourceColumn": "PnL",
            "summarizeBy": "sum"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "765e3546-1dfe-4b6a-b2ad-282e35a1c6f3",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "TraderKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd780208-8703-4d8c-8a33-86bc858dd493",
            "sourceColumn": "TraderKey",
            "summarizeBy": "none"
          },
          {
            "name": "AccountKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a70f1937-5a52-45cb-9f7e-8f38f56fe2fc",
            "sourceColumn": "AccountKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "376b4be7-7025-40dd-aa6a-9f778a627c36",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3388f398-8f03-445f-9c9e-b20af40d7c87",
        "partitions": [
          {
            "name": "FactTrade",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    // 1. Load source table",
                "    Source = TradeInformationBase,",
                "",
                "    // 2. Remove columns NOT needed for FactTradeDaily loading",
                "    //    All dimensional attributes will come from DimTrade, DimTrader, DimProduct, DimAccount",
                "    RemovedUnnecessaryColumns =",
                "        Table.RemoveColumns(",
                "            Source,",
                "            {",
                "                \"CompanyCode\", \"Type\", \"RecordSource\", \"TradeType\", \"TradelineStatus\", ",
                "                \"Direction\", \"MatchIndicator\", \"DealDate\", \"Closed Date\",",
                "                \"L1_ProductGroup\", \"L2_Subgroup\", \"L3_Category\", \"L4_SubCategory\",",
                "                \"Inter Company Account\", \"Account Country\", \"Job Position\"",
                "            }",
                "        ),",
                "",
                "    // 3. Add composite business keys for safe dimension lookups",
                "    AddedTraderKey =",
                "        Table.AddColumn(",
                "            RemovedUnnecessaryColumns,",
                "            \"TraderKey\",",
                "            each [Trader] & \"-\" & [Department],",
                "            type text",
                "        ),",
                "",
                "    AddedAccountKey =",
                "        Table.AddColumn(",
                "            AddedTraderKey,",
                "            \"AccountKey\",",
                "            each [AccountName] & \"-\" & [Account Parent],",
                "            type text",
                "        ),",
                "",
                "    AddedProductKey =",
                "        Table.AddColumn(",
                "            AddedAccountKey,",
                "            \"ProductKey\",",
                "            each [ProductNumber2] & \"-\" & [UnitOfMeasure],",
                "            type text",
                "        ),",
                "",
                "    // 4. Remove natural key columns (they are now replaced by business key columns)",
                "    RemovedNaturalKeys =",
                "        Table.RemoveColumns(",
                "            AddedProductKey,",
                "            {\"Trader\", \"Department\", \"AccountName\", \"Account Parent\", \"ProductNumber2\", \"UnitOfMeasure\"}",
                "        ),",
                "",
                "    // 5. Reorder columns for readability",
                "    ReorderedColumns =",
                "        Table.ReorderColumns(",
                "            RemovedNaturalKeys,",
                "            {",
                "                \"TraderKey\",",
                "                \"AccountKey\",",
                "                \"ProductKey\",",
                "                \"TradelineNumber\",",
                "                \"PnlSplitPercentage\",",
                "                \"Volume\",",
                "                \"Price\",",
                "                \"MtM Price\",",
                "                \"COGS\",",
                "                \"Revenue\",",
                "                \"PnL\",",
                "                \"Currency\"",
                "            }",
                "        )",
                "in",
                "    ReorderedColumns"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "362f3181-9f3f-428a-a3d2-c02821b80215",
        "measures": [
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(FactTrade[Revenue])",
            "lineageTag": "d7a67f64-5698-4395-b22a-6729a8de4c08"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}